Add TaggedAddresses to service register
silas/node-consul pull request #104
Opened 2020-10-19 08:51 UTC by baranovpavel

Add option to register TaggedAdresses
https://www.consul.io/api-docs/agent/service#taggedaddresses

2020-10-19 15:07 UTC, silas requested changes

2020-10-20 06:37 UTC, baranovpavel commented on lib/utils.js
> +
fixed

2020-10-20 12:04 UTC, silas approved these changes

2020-10-20 12:05 UTC, merged

2020-10-20 12:10 UTC, silas commented
Thanks for the PR!

Released to npm in `consul@0.39.0`